In [59]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import re
import ipywidgets as widgets
import plotly.express as px
import plotly.graph_objects as go
%matplotlib inline

In [60]:
#Imports refugee population data from csv

refugee_data_df = pd.read_csv("RefugeePop.csv")

#drops na values
refugee_data_df.dropna(inplace = True)

#stores list of country names to be added later
country_name = refugee_data_df["Country Name"]

#drops non-numeric columns changes numbers to floats
refugee_data_df = refugee_data_df.drop(["Country Name", "Country Code"], axis = 1)
refugee_data_df = refugee_data_df.astype(float)

#cleans up date formating and re-adds it 
refugee_data_columns = refugee_data_df.columns.str.replace('\[\w+\]','', regex=True)
refugee_data_df.columns = refugee_data_columns

#Re-adds the countries and sets them as the index
ref_total = refugee_data_df
ref_total["Country Name"] = country_name
ref_total = ref_total.set_index("Country Name")
ref_total

,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
Country Name,,,,,,,,,,,,,,,,,,,,,
American Samoa,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
Andorra,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,5.0,6.0,5.0,5.0,5.0,1.0,1.0,1.0,1.0,1.0
Aruba,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
Bermuda,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
British Virgin Islands,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Luxembourg,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,5.0,1.0
Malta,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,5.0,5.0,5.0,1.0,1.0,1.0,1.0,5.0,5.0,1.0
Monaco,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,1.0
Norway,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,5.0,5.0,15.0,15.0,10.0,10.0,15.0,5.0,5.0,1.0
Switzerland,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,20.0,16.0,11.0,16.0,16.0,5.0,5.0,5.0,5.0,1.0

In [61]:
#Create Refugee Rate of Change DF
refugee_data_df["Country Name"] = country_name
refugee_data_df = refugee_data_df.drop(["Country Name"], axis = 1)

#Uses pct_method to return year over year %change
ref_pct_change  = refugee_data_df.pct_change(periods = 1,axis=1)

ref_pct_change["Country Name"] = country_name
ref_pct_change = ref_pct_change.set_index("Country Name")

ref_pct_change = ref_pct_change.fillna(0)
ref_pct_change

,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
Country Name,,,,,,,,,,,,,,,,,,,,,
American Samoa,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.000000,0.000000,0.0000,0.0,0.000000,0.0,0.0
Andorra,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.2,-0.166667,0.000000,0.000000,-0.8000,0.0,0.000000,0.0,0.0
Aruba,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.000000,0.000000,0.0000,0.0,0.000000,0.0,0.0
Bermuda,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.000000,0.000000,0.0000,0.0,0.000000,0.0,0.0
British Virgin Islands,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.000000,0.000000,0.0000,0.0,0.000000,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Luxembourg,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.000000,0.000000,0.0000,0.0,0.000000,4.0,-0.8
Malta,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,-0.800000,0.000000,0.0000,0.0,4.000000,0.0,-0.8
Monaco,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,4.0,0.0,0.000000,0.000000,0.000000,0.0000,0.0,0.000000,0.0,-0.8
Norway,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,4.0,0.0,2.000000,0.000000,-0.333333,0.0000,0.5,-0.666667,0.0,-0.8
Switzerland,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,-0.2,-0.312500,0.454545,0.000000,-0.6875,0.0,0.000000,0.0,-0.8

In [62]:
#Population Rate of Change 

#same data cleaning process detailed second cell

pop_pct_change = pd.read_csv("pop_growth.csv")
pop_country_name = pop_pct_change["Country Name"]
pop_pct_change = pop_pct_change.drop(["Country Name","Country Code", "Series Name","Series Code"], axis = 1)
#pop_pct_change = pop_pct_change.replace(r'^..$', 0, regex=True).astype(float)
pop_pct_change = pop_pct_change.astype(float)
pop_pct_change = pop_pct_change.astype(float)
pop_pct_columns = pop_pct_change.columns.str.replace('\[\w+\]','', regex=True)
pop_pct_change.columns = pop_pct_columns
pop_pct_change["Country Name"] = pop_country_name
pop_pct_change = pop_pct_change.set_index("Country Name")

pop_pct_change

,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
Country Name,,,,,,,,,,,,,,,,,,,,,
Afghanistan,1.0,1.898476,1.965751,2.029893,2.090248,2.147567,2.171009,2.188108,2.254572,2.384721,...,3.143126,3.407587,3.494589,3.355582,3.077084,2.778317,2.548347,2.384761,2.311817,1.0
Albania,1.0,3.120855,3.056731,2.953749,2.880686,2.754021,2.634564,2.630190,2.842511,2.896083,...,-0.269017,-0.165151,-0.183211,-0.207047,-0.291206,-0.159880,-0.091972,-0.246732,-0.426007,1.0
Algeria,1.0,2.487165,2.469954,2.490075,2.559731,2.658017,2.763975,2.845359,2.884959,2.872224,...,1.883314,1.951415,2.002728,2.033592,2.045387,2.051355,2.044953,2.007374,1.933950,1.0
American Samoa,1.0,2.352472,3.110990,3.608865,3.653944,3.516676,3.282798,3.162605,2.892643,2.710255,...,-0.572258,-0.165132,0.082600,0.139905,0.037633,-0.127294,-0.217311,-0.279066,-0.276231,1.0
Andorra,1.0,6.941532,6.692697,6.559522,6.241511,5.998800,5.750878,5.500706,5.309820,5.198287,...,-0.834745,-1.588730,-2.025792,-1.951470,-1.529058,-0.919470,-0.383674,0.006493,0.176454,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Virgin Islands (U.S.),1.0,5.390526,2.020271,12.851885,2.481517,6.407886,6.021886,6.087924,12.612111,7.935196,...,-0.060928,-0.093310,-0.135963,-0.148198,-0.161415,-0.185856,-0.225349,-0.271652,-0.323958,1.0
West Bank and Gaza,1.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,2.525187,2.467687,2.400848,2.344077,2.290480,2.246105,1.988686,2.533011,2.511782,1.0
"Yemen, Rep.",1.0,1.450869,1.484101,1.506678,1.515090,1.515578,1.533225,1.563083,1.578205,1.573450,...,2.779988,2.757339,2.716520,2.654141,2.578072,2.498247,2.424025,2.357023,2.300580,1.0
Zambia,1.0,3.001073,2.998554,3.004536,3.022485,3.049879,3.074830,3.099731,3.136268,3.186062,...,3.020291,3.102770,3.139812,3.121305,3.066875,3.003346,2.951583,2.912801,2.892373,1.0
Zimbabwe,1.0,3.342091,3.378041,3.395952,3.391104,3.373423,3.346808,3.328459,3.334673,3.370993,...,1.536391,1.698001,1.777645,1.754692,1.663813,1.549759,1.460061,1.410783,1.419681,1.0

In [63]:
#GDP Rate of change
    #same data cleaning process detailed second cell
GDP_pct_change = pd.read_csv("GDP_Growth.csv")
GDP_country_name = GDP_pct_change["Country Name"]
GDP_pct_change = GDP_pct_change.drop(["Country Name","Country Code", "Series Name","Series Code"],axis = 1)
#GDP_pct_change = GDP_pct_change.replace(r'^..$', 0, regex=True).astype(float)
GDP_pct_change = GDP_pct_change.astype(float)
GDP_pct_change["Country Name"] = GDP_country_name
GDP_pct_change = GDP_pct_change.set_index("Country Name")

GDP_pct_columns = GDP_pct_change.columns.str.replace('\[\w+\]','', regex=True)
GDP_pct_change.columns = GDP_pct_columns

GDP_pct_change

,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
Country Name,,,,,,,,,,,,,,,,,,,,,
Afghanistan,1.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,0.426355,12.752287,5.600745,2.724543,1.451315,2.260314,2.665292,1.840089,2.901229,1.0
Albania,1.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,2.545322,1.417526,1.001987,1.774487,2.218752,3.314805,3.802197,4.071301,2.214063,1.0
Algeria,1.0,-13.605441,-19.685042,34.313729,5.839413,6.206898,-4.804971,9.452963,10.796239,8.433280,...,2.900000,3.400000,2.800000,3.800000,3.700000,3.200000,1.300000,1.400000,0.800000,1.0
American Samoa,1.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,0.293686,-4.392387,-2.756508,0.944882,1.404056,-2.769231,-5.854430,2.184874,1.000000,1.0
Andorra,1.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,-0.008070,-4.974444,-3.547597,2.504466,1.434140,3.709678,0.346072,1.588765,1.849238,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Virgin Islands (U.S.),1.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,-8.158453,-15.019255,-5.830816,-0.866218,0.194175,0.904393,-1.696543,1.000000,1.000000,1.0
West Bank and Gaza,1.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,12.413636,6.284236,2.217422,-0.181891,3.428732,4.708435,3.140237,0.905278,1.000000,1.0
"Yemen, Rep.",1.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,-12.714823,2.392886,4.823415,-0.188591,-27.994439,-9.375060,-5.072010,0.752599,1.000000,1.0
Zambia,1.0,1.361382,-2.490839,3.272393,12.214048,16.647456,-5.570310,7.919697,1.248330,-0.436916,...,5.564602,7.597593,5.057491,4.697729,2.919980,3.776775,3.504326,4.034812,1.705793,1.0
Zimbabwe,1.0,6.316157,1.434471,6.244345,-1.106172,4.910571,1.523130,8.367009,1.970135,12.428236,...,14.193913,16.665429,1.989493,2.376929,1.779873,0.755869,4.704035,4.829674,-8.100000,1.0

In [64]:
#creates a dropdown with a list of the countries in alphabetical order (series genderated above)

drop_down = widgets.Dropdown(options=list(pop_country_name),
                                                    #sets "Afghanistan" as the default
                                value="Afghanistan",
                                                      #sets name of dropdown
                                description='Countries',
                                disabled=False)

                #the user's selection then becomes the input of the function.
                #which in this case is a string of the country name 
def generate_graph(country): 
                                
                                #since the 'pop_country_name' list used to make the drop down 
                                #is the same that was used to make the indexes of dataframes
                                #the list values match exactly and can be used in loc statements
                                #to narrow down the df to just the country the user selected
    GDP = pd.DataFrame(GDP_pct_change.loc[country,:])
    pop = pd.DataFrame(pop_pct_change.loc[country,:])    #stores the .loc returns as variables 
    ref = pd.DataFrame(ref_pct_change.loc[country,:])
    t_ref = pd.DataFrame(ref_total.loc[country,:])
    
                                            #uses Plotly to graph the lines 
    fig1 = px.line(GDP, template= "plotly_dark", title=f"{country} GDP % Change")
    fig2 = px.line(pop, template= "plotly_dark", title=f"{country} Population % Change")
    fig3 = px.line(ref, template= "plotly_dark", title=f"{country} Refugee Population % Change")
    fig4 = px.line(t_ref, template= "plotly_dark", title=f"{country} Total Refugee Count")
                    #the function returns the graph display calls
    return fig1.show(), fig2.show(), fig4.show() #fig3.show(),

#this calls the widget and sets the 'country' variable to the input
#which is used as the input for the function above
widgets.interact(generate_graph, country=drop_down);

interactive(children=(Dropdown(description='Countries', options=('Afghanistan', 'Albania', 'Algeria', 'America…

In [65]:
#imports additional plotly library
import plotly.figure_factory as ff

#same process detailed in the cell above
drop_down = widgets.Dropdown(options=list(pop_country_name),
                                value="Afghanistan",
                                description='Countries',
                                disabled=False)
def generate_distplot(country): 

        # Add histogram data (same .loc process as before)
        #uses list function to convert them to the format Plotly displot accepts
    x1 = list(GDP_pct_change.loc[country,:])
    x2 = list(pop_pct_change.loc[country,:])
    x3 = pd.DataFrame(ref_total.loc[country,:])


    # displot takes as an argument 2 lists
    hist1_data = [x1, x2]
    hist2_data = [x3]

    group_labels = ['%GDP Change', '%Pop Change']
    label = ['Refugee Population']
    
    # Create distplot 
    fig1 = ff.create_distplot(hist1_data, group_labels, bin_size=.2)
    fig2 = px.bar(x3, title=f"{country} Refugee Population")
    
    return fig1.show(), fig2.show()

widgets.interact(generate_distplot, country=drop_down);

interactive(children=(Dropdown(description='Countries', options=('Afghanistan', 'Albania', 'Algeria', 'America…

In [66]:
#Used same data cleaning process detailed in cell 2 
#Created this to use a more reliable metric for economic health/growth
#GDP perchasing power per capita % change over time
#Uses pct_method to return year over year %change

GDP_per_cap_df = pd.read_csv("GDP_per_cap.csv")
country_names = GDP_per_cap_df["Country Name"]

GDP_per_cap_change = GDP_per_cap_df.drop(["Country Name","Country Code", "Series Name","Series Code"], axis=1)
#GDP_per_cap_change = GDP_per_cap_change.replace(r'^..$', 1, regex=True).astype(float)
GDP_per_cap_change =GDP_per_cap_change.astype(float)
GDP_per_cap_change = GDP_per_cap_change.pct_change(periods = 1, fill_method='pad',axis=1)

GDP_per_cap_change["Country Name"] = country_names
GDP_per_cap_change = GDP_per_cap_change.set_index("Country Name")

GDP_per_cap_change = GDP_per_cap_change.fillna(0)
GDP_per_cap_change

GDP_per_cap_columns = GDP_per_cap_change.columns.str.replace('\[\w+\]','', regex=True)
GDP_per_cap_change.columns = GDP_per_cap_columns


GDP_per_cap_change = GDP_per_cap_change.T

GDP_per_cap_change

Country Name,Afghanistan,Albania,Algeria,American Samoa,Andorra,Angola,Antigua and Barbuda,Argentina,Armenia,Aruba,...,Uruguay,Uzbekistan,Vanuatu,"Venezuela, RB",Vietnam,Virgin Islands (U.S.),West Bank and Gaza,"Yemen, Rep.",Zambia,Zimbabwe
1960,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.000000
1961,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.000000
1962,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.000000
1963,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.000000
1964,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2016,0.019970,0.029236,-0.032569,0.0,0.0,-0.031937,0.053218,0.010081,0.073678,0.016164,...,0.022368,0.017307,0.018971,0.0,0.077091,0.0,0.017489,0.0,-0.007504,0.047378
2017,0.034562,0.086152,-0.006345,0.0,0.0,0.029237,-0.003952,0.160285,0.131801,0.028990,...,0.031690,0.010209,0.037216,0.0,0.088642,0.0,0.047255,0.0,0.023597,0.079027
2018,0.017867,0.061131,0.017300,0.0,0.0,-0.029242,0.089414,-0.011895,0.074282,-0.999974,...,0.036364,0.060760,0.026474,0.0,0.085198,0.0,0.007029,0.0,0.034326,0.058001
2019,0.023029,0.047788,0.005932,0.0,0.0,-0.023593,0.055630,-0.014410,0.092558,0.000000,...,0.016034,0.054068,0.021904,0.0,0.078430,0.0,-0.999827,0.0,0.005291,-0.078156
2020,-0.999564,-0.999931,-0.999915,0.0,0.0,-0.999856,-0.999956,-0.999956,-0.999930,0.000000,...,-0.999955,-0.999863,-0.999695,0.0,-0.999881,0.0,0.000000,0.0,-0.999724,-0.999661

In [67]:
#Population total Data Frame
#same cleaning process as cell 2

pop_total_df = pd.read_csv("total_pop.csv")
country_names = pop_total_df["Country Name"]

pop_total_df = pop_total_df.drop(["Country Name","Country Code", "Series Name","Series Code"], axis=1)
# #pop_total_df = pop_total_df.replace(r'^..', 0, regex=True)
pop_total_df = pop_total_df.astype(float)

pop_total_df["Country Name"] = country_names
pop_total_df = pop_total_df.set_index("Country Name")

pop_total_df = pop_total_df.fillna(0)

pop_total_columns = pop_total_df.columns.str.replace('\[\w+\]','', regex=True)
pop_total_df.columns = pop_total_columns

pop_total_df

,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
Country Name,,,,,,,,,,,,,,,,,,,,,
Afghanistan,8996973.0,9169410.0,9351441.0,9543205.0,9744781.0,9956320.0,10174836.0,10399926.0,10637063.0,10893776.0,...,30117413.0,31161376.0,32269589.0,33370794.0,34413603.0,35383128.0,36296400.0,37172386.0,38041754.0,1.0
Albania,1608800.0,1659800.0,1711319.0,1762621.0,1814135.0,1864791.0,1914573.0,1965598.0,2022272.0,2081695.0,...,2905195.0,2900401.0,2895092.0,2889104.0,2880703.0,2876101.0,2873457.0,2866376.0,2854191.0,1.0
Algeria,11057863.0,11336339.0,11619828.0,11912803.0,12221675.0,12550885.0,12902627.0,13275026.0,13663583.0,14061722.0,...,36661444.0,37383887.0,38140132.0,38923687.0,39728025.0,40551404.0,41389198.0,42228429.0,43053054.0,1.0
American Samoa,20123.0,20602.0,21253.0,22034.0,22854.0,23672.0,24462.0,25248.0,25989.0,26703.0,...,55759.0,55667.0,55713.0,55791.0,55812.0,55741.0,55620.0,55465.0,55312.0,1.0
Andorra,13411.0,14375.0,15370.0,16412.0,17469.0,18549.0,19647.0,20758.0,21890.0,23058.0,...,83747.0,82427.0,80774.0,79213.0,78011.0,77297.0,77001.0,77006.0,77142.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Virgin Islands (U.S.),32500.0,34300.0,35000.0,39800.0,40800.0,43500.0,46200.0,49100.0,55700.0,60300.0,...,108292.0,108191.0,108044.0,107884.0,107710.0,107510.0,107268.0,106977.0,106631.0,1.0
West Bank and Gaza,1.0,1.0,1.0,1.0,1.0,1.0,1978248.0,1978248.0,1978248.0,1978248.0,...,3882986.0,3979998.0,4076708.0,4173398.0,4270092.0,4367088.0,4454805.0,4569087.0,4685306.0,1.0
"Yemen, Rep.",5315355.0,5393036.0,5473671.0,5556766.0,5641597.0,5727751.0,5816247.0,5907874.0,6001852.0,6097035.0,...,23807588.0,24473178.0,25147109.0,25823485.0,26497889.0,27168210.0,27834821.0,28498687.0,29161922.0,1.0
Zambia,3070776.0,3164329.0,3260650.0,3360104.0,3463213.0,3570464.0,3681955.0,3797873.0,3918872.0,4045740.0,...,14023193.0,14465121.0,14926504.0,15399753.0,15879361.0,16363507.0,16853688.0,17351822.0,17861030.0,1.0
Zimbabwe,3776681.0,3905034.0,4039201.0,4178726.0,4322861.0,4471177.0,4623351.0,4779827.0,4941906.0,5111337.0,...,12894316.0,13115131.0,13350356.0,13586681.0,13814629.0,14030390.0,14236745.0,14439018.0,14645468.0,1.0

In [68]:
#Creates Refugee population per capita by dividing the total refugee count by the total population

ref_per_cap = ref_total.div(pop_total_df)

ref_per_cap = ref_per_cap.T
ref_per_cap

Country Name,Afghanistan,Albania,Algeria,American Samoa,Andorra,Angola,Antigua and Barbuda,Argentina,Armenia,Aruba,...,Uruguay,Uzbekistan,Vanuatu,"Venezuela, RB",Vietnam,Virgin Islands (U.S.),West Bank and Gaza,"Yemen, Rep.",Zambia,Zimbabwe
1960,1.111485e-07,6.215813e-07,9.043339e-08,0.000050,0.000075,0.027498,0.000018,4.882388e-08,5.335835e-07,0.000018,...,3.939112e-07,1.172842e-07,0.000016,1.228223e-07,3.060908e-08,0.000031,1.000000,1.881342e-07,3.256506e-07,2.647828e-07
1961,1.090583e-07,6.024822e-07,8.821190e-08,0.000049,0.000070,0.027118,0.000018,4.803705e-08,5.150678e-07,0.000018,...,3.888507e-07,1.134608e-07,0.000015,1.184938e-07,2.970346e-08,0.000029,1.000000,1.854243e-07,3.160228e-07,2.560797e-07
1962,1.069354e-07,5.843446e-07,8.605979e-08,0.000047,0.000065,0.030311,0.000018,4.727450e-08,4.976298e-07,0.000018,...,3.840420e-07,1.097259e-07,0.000015,1.143801e-07,2.883223e-08,0.000029,1.000000,1.826927e-07,3.066873e-07,2.475737e-07
1963,1.047866e-07,5.673369e-07,8.394330e-08,0.000045,0.000061,0.030813,0.000018,4.653563e-08,4.813297e-07,0.000018,...,3.794885e-07,1.060568e-07,0.000014,1.104651e-07,2.799457e-08,0.000025,1.000000,1.799608e-07,2.976098e-07,2.393074e-07
1964,1.026190e-07,5.512269e-05,8.182185e-08,0.000044,0.000057,0.034873,0.000017,4.582022e-08,7.925404e-05,0.000018,...,3.751799e-07,1.024295e-07,0.000014,1.067339e-07,2.718869e-04,0.000025,1.000000,1.772548e-07,2.887492e-07,2.313283e-07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2016,7.069604e-02,3.845484e-03,9.136552e-05,0.000018,0.000013,0.000291,0.000867,2.752902e-06,3.646617e-03,0.000010,...,6.717031e-06,1.200707e-04,0.000004,2.527292e-04,3.517145e-03,0.000009,0.022393,6.782559e-04,1.564457e-05,1.292979e-03
2017,7.230097e-02,4.234621e-03,9.715095e-05,0.000018,0.000013,0.000278,0.001037,2.747202e-06,3.662716e-03,0.000009,...,3.491777e-06,1.051296e-04,0.000004,3.154771e-04,3.531457e-03,0.000009,0.022365,8.462422e-04,1.542689e-05,1.223594e-03
2018,7.213061e-02,4.713966e-03,9.912753e-05,0.000018,0.000013,0.000268,0.001111,2.517165e-06,3.740121e-03,0.000009,...,2.029398e-06,9.940497e-05,0.000003,7.290217e-04,3.500760e-03,0.000009,0.022046,1.092857e-03,1.532980e-05,1.081653e-03
2019,7.173310e-02,5.264889e-03,1.048474e-04,0.000018,0.000013,0.000257,0.001205,2.203000e-06,3.706219e-03,0.000009,...,4.333089e-06,9.579922e-05,0.000003,3.271166e-03,3.280470e-03,0.000009,0.020557,1.252249e-03,1.461282e-05,7.239782e-04
2020,1.000000e+00,1.000000e+00,1.000000e+00,1.000000,1.000000,1.000000,1.000000,1.000000e+00,1.000000e+00,1.000000,...,1.000000e+00,1.000000e+00,1.000000,1.000000e+00,1.000000e+00,1.000000,1.000000,1.000000e+00,1.000000e+00,1.000000e+00

In [69]:
#transposes df to same orientation as others 
pop_pct_change = pop_pct_change.T

#creates a slider with min/max values that match the years available in data set 
slider = widgets.IntRangeSlider(
    value=[1960, 2020],  #the user selection returns a list. e.g [1975, 1982] =years 1975-1982
    min=1960,
    max=2020,
    step=1,
    description='Year Range:',
    disabled=False,
    continuous_update=False,
    orientation='horizontal',
    readout=True,
    readout_format='d',
)

def generate_bubbles(duration):   #this is the same slider/user selection mentioned above ^
                                    #it's then passed as the parameters of the function
                                        #e.g [1975, 1982]
            
        #the indexes of the data frames are the years
        #e.g. GDP_per_cap_change.loc[1975:1982,:].mean() -returns avg gdp change between 1975-1982
    gdp = GDP_per_cap_change.loc[str(duration[0]):str(duration[1]),:].mean()
    pop = pop_pct_change.loc[str(duration[0]):str(duration[1]),:].mean()
    cap = ref_per_cap.loc[str(duration[0]):str(duration[1]),:].mean()

        #creates df with metrics generated above
    grph_dict = {"GDPPP per cap":gdp, "Population Growth":pop, "Ref Pop per cap":cap}
    grph_df = pd.DataFrame(grph_dict)
    grph_df = grph_df.reset_index()


          #uses Plotly to generate bubble plot 
        #'size' means bubble size so they get bigger the more refugees per capita
    fig = px.scatter(grph_df, x= "GDPPP per cap", y="Population Growth", size="Ref Pop per cap",
                     hover_name = "Country Name", color="Ref Pop per cap", log_x=True)
            #function returns the chart
        #generates a new chart every time the slider is changed 
        #because that changes the parameters of the function (the date ranges)
    return fig.show()

#displays widget and calls function with the values selected
widgets.interact(generate_bubbles, duration=slider);

interactive(children=(IntRangeSlider(value=(1960, 2020), continuous_update=False, description='Year Range:', m…

In [56]:
ref_total = ref_total.T
                                   #same slider process detailed in the celll above
slider2 = widgets.IntRangeSlider(
    value=[1960, 2020],
    min=1960,
    max=2020,
    step=1,
    description='Year Range:',
    disabled=False,
    continuous_update=False,
    orientation='horizontal',
    readout=True,
    readout_format='d',
)
                    #e.g. ref_total.loc[1975:1982,:] returns total counts of refugees 1975-1982
def bar_chart(duration):
    timeframe = ref_total.loc[str(duration[0]):str(duration[1]),:]
    avg_ref_pop = timeframe.mean()
    y = avg_ref_pop.values
    x = ref_total.columns

    #hovertext defaults to index (country name)
    fig = go.Figure(data=[go.Bar(x=x, y=y)])
    # Customize aspect
    fig.update_traces(marker_color='rgb(158,202,225)' , marker_line_color='rgb(8,48,107)',
                      marker_line_width=1.5, opacity=0.6)
    fig.update_layout(template= "plotly_dark",title_text='Avg Refugee Population for Timeframe')
    return fig.show()

widgets.interact(bar_chart, duration=slider);

interactive(children=(IntRangeSlider(value=(1991, 2007), continuous_update=False, description='Year Range:', m…

In [57]:
#creates host/country of asylum data with same process detailed in cell 2

ref_host = pd.read_csv("refugee_host.csv")
ref_host.dropna(inplace = True)
country_name = ref_host["Country Name"]


ref_host = ref_host.drop(["Country Name","Country Code", "Series Name","Series Code"],axis = 1)
ref_host = ref_host.astype(float)

refugee_data_columns = ref_host.columns.str.replace('\[\w+\]','', regex=True)
ref_host.columns = refugee_data_columns

ref_host = ref_host

ref_host["Country Name"] = country_name
ref_host = ref_host.set_index("Country Name")
ref_host

,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
Country Name,,,,,,,,,,,,,,,,,,,,,
Afghanistan,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,3011.0,16184.0,16861.0,300421.0,257553.0,59770.0,75927.0,72228.0,72227.0,0.0
Albania,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,79.0,84.0,96.0,111.0,109.0,141.0,124.0,132.0,120.0,0.0
Algeria,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,94145.0,94130.0,94142.0,94119.0,94176.0,94220.0,94248.0,94341.0,98599.0,0.0
American Samoa,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Andorra,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Virgin Islands (U.S.),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
West Bank and Gaza,258165.0,265430.0,273038.0,283782.0,293024.0,301879.0,311846.0,295040.0,576889.0,580025.0,...,1895043.0,1944544.0,1994493.0,2051096.0,2104001.0,2158274.0,2214783.0,2267747.0,2319073.0,0.0
"Yemen, Rep.",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,214736.0,237176.0,241281.0,257637.0,267163.0,269778.0,270913.0,264359.0,268503.0,0.0
Zambia,0.0,0.0,0.0,0.0,0.0,5000.0,6290.0,10710.0,13190.0,12640.0,...,45627.0,25647.0,23584.0,25566.0,26434.0,29338.0,41266.0,49877.0,57518.0,0.0
Zimbabwe,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,4559.0,4354.0,6387.0,6076.0,6943.0,7423.0,7566.0,7795.0,8956.0,0.0

In [58]:
ref_host = ref_host.T
                        #exact same process in the graph above just with host country data
slider3 = widgets.IntRangeSlider(
    value=[1960, 2020],
    min=1960,
    max=2020,
    step=1,
    description='Year Range:',
    disabled=False,
    continuous_update=False,
    orientation='horizontal',
    readout=True,
    readout_format='d',
)

def bar_chart(duration):
    timeframe = ref_host.loc[str(duration[0]):str(duration[1]),:]
    avg_ref_pop = timeframe.mean()
    y = avg_ref_pop.values
    x = ref_host.columns

    # Use the hovertext kw argument for hover text
    fig = go.Figure(data=[go.Bar(x=x, y=y)])
    # Customize aspect
    fig.update_traces(marker_color='rgb(158,202,225)' , marker_line_color='rgb(8,48,107)',
                      marker_line_width=1.5, opacity=0.6)
    fig.update_layout(template= "plotly_dark",title_text='Avg Refugee Asylum Population')
    return fig.show()

widgets.interact(bar_chart, duration=slider);

interactive(children=(IntRangeSlider(value=(1991, 2007), continuous_update=False, description='Year Range:', m…